package com.example.project.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

/**
 * Stores the float[] embedding vector for a property as a JSON blob.
 * Generated by EmbeddingService after create/update; used for semantic
 * similarity search (recommendations) and duplicate-listing fraud detection.
 */
@Entity
@Table(name = "property_embeddings")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PropertyEmbedding {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "property_id", nullable = false, unique = true)
    private Property property;

    /**
     * JSON-serialised float[] from OpenAI text-embedding-3-small (1536 dims).
     * Stored as LONGTEXT — no pgvector dependency required.
     */
    @Column(columnDefinition = "LONGTEXT", nullable = false)
    private String embeddingJson;

    @Builder.Default
    @Column(name = "updated_at")
    private LocalDateTime updatedAt = LocalDateTime.now();
}
